bookstore/Areas/Admin/Controllers/CustomerTypeController.cs
using bookstore.Areas.Admin.Models;
using bookstore.DbContext;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace bookstore.Areas.Admin.Controllers
{
    [Area("admin")]
    [Route("/admin/CustomerType")]
    [Authorize(Roles = Role.Role_Admin + "," + Role.Role_Employee)]

    public class CustomerTypeController : Controller
    {
        readonly private ApplicationDbContext _db;
        readonly private IToastNotification _toastNotification;

        public CustomerTypeController(ApplicationDbContext db, IToastNotification toastNotification)
        {
            _db = db;
            _toastNotification = toastNotification;

        }

        public IActionResult Index()
        {
            IEnumerable<CustomerTypeModel> customerTypes = _db.CustomerTypes.ToList();



            return View(customerTypes);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> create(CustomerTypeModel obj)
        {

            await _db.CustomerTypes.AddAsync(obj);

            await _db.SaveChangesAsync();

            _toastNotification.AddSuccessToastMessage("tạo bậc thành viên thành công");
            return RedirectToAction("index");

        }

        [Route("delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {

            var customerType = await _db.CustomerTypes.FindAsync(id);

            if (customerType == null)
            {
                _toastNotification.AddErrorToastMessage("Không tìm thấy bậc hội viên");

                return RedirectToAction("index");
            }

            _db.CustomerTypes.Remove(customerType);

            await _db.SaveChangesAsync();

            _toastNotification.AddSuccessToastMessage("Xóa bậc hội viên thành công");

            return RedirectToAction("index");

        }

        [Route("edit/{id}")]
        public IActionResult edit(int id)
        {
            var customerType = _db.CustomerTypes.Find(id);

            return View(customerType);
        }

        [Route("editpost")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> editpost([Bind("Id,Name")] CustomerTypeModel obj)
        {
            var customerType = await _db.CustomerTypes.FindAsync(obj.Id);
            if (customerType == null)
            {
                _toastNotification.AddErrorToastMessage("không thể sửa bậc hội viên");
                return RedirectToAction("index");
            }


            customerType.Name = obj.Name;
            await _db.SaveChangesAsync();

            _toastNotification.AddSuccessToastMessage("chỉnh sửa bậc hội viên thành công");
            return RedirectToAction("index");
        }
    }
}

bookstore/Areas/Admin/Views/CustomerType/Edit.cshtml
@model bookstore.Areas.Admin.Models.CustomerTypeModel

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="col-12 grid-margin">
    <div class="card">
        <div class="card-body">
            <button onclick="location.href='@Url.Action("Index","CustomerType")'" class="btn btn-secondary mt-5 mb-5">Trờ về</button>
            <h4 class="card-title">Cấp bậc hội viên</h4>
            <form class="form-sample" method="post" asp-action="EditPost" asp-controller="CustomerType">
             
                <p class="card-description">
                    Thông tin cấp bậc thành viên
                </p>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Id</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" value="@Model.Id" asp-for="Id"  />
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Tên cấp bậc thành viên</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" value="@Model.Name" asp-for="Name" />
                            </div>
                        </div>
                    </div>

                </div>
            

                <button type="submit" class="btn btn-success" >Lưu</button>


            </form>
        </div>
    </div>
</div>

bookstore/Areas/Admin/Views/CustomerType/Index.cshtml
@model IEnumerable<bookstore.Areas.Admin.Models.CustomerTypeModel>


@{
    ViewData["Title"] = "Phương thức giao hàng";
}

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}
<div class="mt-5 mb-5">
    <button class="btn btn-success" data-toggle="modal" data-target="#exampleModal">Thêm cấp bậc hội viên</button>
</div>

<table class="table">

    <thead>

        <tr>
            <td>Id</td>
            <td>Tên cấp bậc hội viên</td>
       
       
        
        </tr>
    </thead>

    <tbody>

        @foreach (var obj in Model)
        {
            <tr>
                <td>@obj.Id</td>
                <td>@obj.Name</td>
             
                <td>
                    <button onclick="location.href='@Url.Action("Edit","CustomerType",new{id = obj.Id})'" class="btn btn-primary">Chỉnh sửa</button>
                    <button class="btn btn-danger"
                            onclick="
              if(confirm('Bạn có muốn xóa cấp bậc hội viên này?')){
                location.href='@Url.Action("Delete","CustomerType",new{id = @obj.Id})'
              }
            ">
                        Xóa
                    </button>
                </td>
            </tr>
        }

    </tbody>

</table>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">

    <div class="modal-dialog" role="document" style="max-width: 800px !important;">
        <div class="modal-content" style="max-height: 600px; overflow-y: scroll;">

            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Tạo cấp bậc hội viên</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <form class="form-sample" enctype="multipart/form-data" method="post" asp-action="create">
                <input type="hidden" name="status"  value="1"/>
                <div class="modal-body">

                    <div class="row">

                        <div class="col-sm-12 col-md-12">
                            <div class="form-group">
                                <label>Tên phương bậc hội viên</label>
                                <input type="text" class="form-control font-weight-bold" name="Name" />
                            </div>
                        </div>

      

                     </div>
                </div>


                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Tạo</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                </div>

            </form>

        </div>
    </div>
</div>