bookstore/Areas/Admin/Controllers/GenreController.cs
using bookstore.Areas.Admin.Models;
using bookstore.DbContext;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using NToastNotify;
using System.Collections.Generic;

namespace bookstore.Areas.Admin.Controllers
{

    [Area("admin")]
    [Route("/admin/genre")]
    [Authorize(Roles = Role.Role_Admin + "," + Role.Role_Employee)]

    public class GenreController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IToastNotification _toastNotification;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public GenreController(ApplicationDbContext db,IToastNotification toastNotification,IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _toastNotification = toastNotification;
            _webHostEnvironment = webHostEnvironment;
            
        }

        public IActionResult Index()
        {
            IEnumerable<GenreModel> genreModels = _db.Genres;

            return View(genreModels);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("add")]
        
        public async Task<IActionResult> create(GenreModel obj,IFormFile? imageFile)
        {

            string wwwRootPath = _webHostEnvironment.WebRootPath;

            if (imageFile != null)
            {
                string fileName = Guid.NewGuid().ToString();
                string uploads = Path.Combine(wwwRootPath, @"images\genre");
                var extension = Path.GetExtension(imageFile.FileName);

                await using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    await imageFile.CopyToAsync(fileStreams);
                }
                obj.image = @"\images\genre\" + fileName + extension;

            }

            await _db.Genres.AddAsync(obj);
            await _db.SaveChangesAsync();
            _toastNotification.AddSuccessToastMessage("Thêm thể loại thành công");
            return RedirectToAction("Index");

        }

        [Route("delete/{id}")]

        public async Task<IActionResult> delete(int? id)
        {
            var genre = await _db.Genres.FindAsync(id);
            if (genre == null)
            {
                _toastNotification.AddErrorToastMessage("Xóa thể loại thất bại");

                return RedirectToAction("Index");

            }

            _db.Genres.Remove(genre);

            await _db.SaveChangesAsync();
            _toastNotification.AddSuccessToastMessage("Xóa thể loại thành công");

            return RedirectToAction("Index");



        }

        [Route("edit/{id}")]

        public IActionResult edit(int? id)
        {
            var genre = _db.Genres.Find(id);  
            






            if (genre == null)
            {
                _toastNotification.AddErrorToastMessage("Sản phẩm không tồn tại");

                return RedirectToAction("Index");
            }

            return View(genre);

        }


        [ValidateAntiForgeryToken]
        [HttpPost]
        [Route("editpost")]
        public async Task<IActionResult> editpost([Bind("Id,Name")]GenreModel obj, IFormFile? imageFile)
        {
            var genre = await _db.Genres.FindAsync(obj.Id);

            if (genre == null)
            {
                _toastNotification.AddErrorToastMessage("không tìm thấy sản phẩm");
                return RedirectToAction("Index");
            }

            if (imageFile != null)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                string fileName = Guid.NewGuid().ToString();
                string uploads = Path.Combine(wwwRootPath, @"images\genre");
                var extension = Path.GetExtension(imageFile.FileName);

                await using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    await imageFile.CopyToAsync(fileStreams);
                }
                genre.image = @"\images\genre\" + fileName + extension;

            }
            genre.Name = obj.Name;
            await _db.SaveChangesAsync();
            _toastNotification.AddSuccessToastMessage("Chỉnh sửa thể loại thành công");

            return RedirectToAction("Index");




        }







    }
}

bookstore/Areas/Admin/Views/Genre/Edit.cshtml
@model bookstore.Areas.Admin.Models.GenreModel

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">

            @*<button onclick="location.href='@Url.Action("Index","Genre")'" class="btn btn-secondary mt-5 mb-5">Trờ về</button>*@

            <div class="card-title">Cập nhật thể loại</div>

            <form class="form-sample" method="post" asp-action="editpost" asp-controller="Genre" enctype="multipart/form-data">

                <div class="row">

                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Id</label>
                            <input type="text" class="form-control font-weight-bold" value="@Model.Id" asp-for="Id" readonly/>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Tên thể loại</label>
                            <input type="text" class="form-control font-weight-bold" value="@Model.Name" asp-for="Name" />
                        </div>
                    </div>

                    <div class="col-sm-12">
                            <div class="form-group">
                                <label>Ảnh mô tả</label>
                                <input type="file" name="imageFile" class="file-upload-default" onchange="preview_imageBook()" id="photoInputBook">
                                <div class="input-group col-xs-12">
                                    <span class="">
                                        <button class="file-upload-browse btn btn-primary" type="button">Tải ảnh</button>
                                    </span>
                                </div>
                            </div>
                            <div>
                                <img class="rounded" id="photoBook" src="~/images/logo/default.jpg" width="90px" height="110px" />
                            </div>

                    </div>
                </div>

                <button type="submit" class="btn btn-success">Cập nhật</button>


            </form>
        </div>
    </div>
    </div>
</div>

bookstore/Areas/Admin/Views/Genre/Index.cshtml
@model IEnumerable<bookstore.Areas.Admin.Models.GenreModel>

@{
    ViewData["Title"] = "Thể loại";
}

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}


<div class="row">

    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <div class="card-title">Quản lý thể loại</div>

                <button class="btn btn-success" data-toggle="modal" data-target="#genreAddModal">Thêm thể loại</button>

                <hr />

                <div class="table-responsive">
                    <table class="table">

                        <thead class="table-primary">
                            <tr>
                                <th>Id</th>
                                <th>Tên thể loại</th>
                                <th>Hình ảnh</th>
                                <th>Lựa chọn</th>
                            </tr>
                        </thead>

                        <tbody>

                            @foreach (var obj in Model)
                            {
                                <tr>
                                  <td class="font-weight-bold">@obj.Id</td>
                                  <td class="font-weight-bold">@obj.Name</td>
                                  <td>
                                      <img src="@obj.image" style="border-radius: 0px; height: 80px; width: 60px;"/>
                                  </td>
                                  <td>                    
                                      <button onclick="location.href='@Url.Action("Edit","Genre",new{id = obj.Id})'" class="btn btn-primary" >Chỉnh sửa</button>
                                      <button class="btn btn-danger" onclick="
                                           if(confirm('Bạn có muốn xóa thể loại này?')){
                                                location.href='@Url.Action("Delete","Genre",new{id = @obj.Id})'
                                            }
                                        " >Xóa</button>
                                  </td>
                              </tr>
                            }

                        </tbody>

                    </table>
                </div>

            </div>
        </div>
    </div>

</div>


<div class="modal fade" id="genreAddModal" tabindex="-1" role="dialog" aria-labelledby="genreModalLabel" aria-hidden="true">

  <div class="modal-dialog" role="document">

    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Thêm thể loại</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <form class="form-sample" method="post" asp-action="create" enctype="multipart/form-data">

            <div class="modal-body">
       
                <div class="row">

                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Tên thể loại</label>
                            <input type="text" class="form-control" name="Name" />
                        </div>
                    </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Ảnh thể loại</label>
                                <input type="file" name="imageFile" id="photoInput"  class="file-upload-default" onchange="preview_image();">
                                <div class="input-group col-xs-12">
                                    <span class="">
                                        <button class="file-upload-browse btn btn-primary" type="button">Tải ảnh</button>
                                    </span>
                                </div>
                            </div>
                            <div>
                                <img class="userAvatar rounded" src="~/images/logo/default.jpg" width="90px" height="110px" />
                            </div>
                        </div>

                   
                </div>

             </div>

             <div class="modal-footer">
                 <button type="submit" class="btn btn-primary">Thêm thể loại</button>
                 <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
             </div>

      </form>

    </div>
  </div>
</div>