bookstore/Areas/Admin/Controllers/PublisherController.cs
using bookstore.Areas.Admin.Models;
using bookstore.DbContext;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using System.Security.Policy;

namespace bookstore.Areas.Admin.Controllers
{
    [Area("admin")]
    [Route("/admin/publisher")]
    [Authorize(Roles = Role.Role_Admin + "," + Role.Role_Employee)]

    public class PublisherController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IToastNotification _toastNotification;
        public PublisherController(ApplicationDbContext db, IToastNotification toastNotification) { 
            _db = db;
            _toastNotification = toastNotification; 
        }

        [Route("")]
        public IActionResult Index()
        {
            IEnumerable<PublisherModel> publisherModels = _db.Publisher;

            return View(publisherModels);
        }

        [Route("add")]
        [ValidateAntiForgeryToken]
        [HttpPost]

        public async Task<IActionResult> Create(PublisherModel obj)
        {
            if (obj == null)
            {
                _toastNotification.AddErrorToastMessage("Không thể thêm nhà xuất bản");
                return RedirectToAction("Index");

            }

            await _db.Publisher.AddAsync(obj);
            await _db.SaveChangesAsync();
            _toastNotification.AddSuccessToastMessage("Thêm nhà xuất bản thành công");

            return RedirectToAction("Index");

        }

        [Route("delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            var publisher = await _db.Publisher.FindAsync(id);

            if (publisher == null)
            {
                _toastNotification.AddErrorToastMessage("Không thể xóa nhà xuất bản");
                return RedirectToAction("Index");
            }

             _db.Publisher.Remove(publisher);

            await _db.SaveChangesAsync();
            _toastNotification.AddSuccessToastMessage("Xóa nhà xuất bản thành công");

            return RedirectToAction("Index");

        }

        [Route("edit/{id}")]
        public IActionResult Edit(int? id)
        {
            var publisher = _db.Publisher.Find(id);

            if(publisher == null)
            {
                _toastNotification.AddErrorToastMessage("Không tìm thấy nhà xuất bản");

                return RedirectToAction("Index");
            }

            return View(publisher);



        }

        [Route("editpost")]
        [ValidateAntiForgeryToken][HttpPost]
        public async Task<IActionResult> editpost([Bind("Name,Id")] PublisherModel obj )
        {
            var publisher = await _db.Publisher.FindAsync(obj.Id);
            if (publisher == null)
            {
                _toastNotification.AddErrorToastMessage("Không tìm thấy nhà xuất bản");

                return RedirectToAction("Index");
            }

            publisher.Name = obj.Name;

            await _db.SaveChangesAsync();
            _toastNotification.AddSuccessToastMessage("Chỉnh sửa nhà xuất bản thành công");

            return RedirectToAction("Index");

        }



    }
}

bookstore/Areas/Admin/Views/Publisher/Edit.cshtml
@model bookstore.Areas.Admin.Models.PublisherModel

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12 grid-margin">
    <div class="card">
        <div class="card-body">
            @*<button onclick="location.href='@Url.Action("Index","Publisher")'" class="btn btn-secondary mt-5 mb-5">Trờ về</button>*@

            <div class="card-title">Nhà xuất bản</div>

            <form class="form-sample" method="post" asp-action="editpost" asp-controller="Publisher">
             
                <div class="row">

                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Id</label>
                            <input type="text" class="form-control font-weight-bold" value="@Model.Id" asp-for="Id"  readonly/>
                        </div>
                    </div>

                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Tên Nhà xuất bản</label>
                                 <input type="text" class="form-control font-weight-bold" value="@Model.Name" asp-for="Name" />
                            </div>
                        </div>

                </div>
               

                <button type="submit" class="btn btn-success" >Cập nhật</button>


            </form>
        </div>
    </div>
</div>
</div>

bookstore/Areas/Admin/Views/Publisher/Index.cshtml
@model IEnumerable<bookstore.Areas.Admin.Models.PublisherModel>

@{
    ViewData["Title"] = "Nhà xuất bản";
}

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}
<div class="row">

    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <div class="card-title">Quản lý nhà xuất bản</div>

                <button class="btn btn-success" data-toggle="modal" data-target="#publisherAddModal">Thêm nhà xuất bản</button>

                <hr />

                <div class="table-responsive">
                    <table class="table">

                        <thead class="table-primary">
                            <tr>
                                <th>Id</th>
                                <th>Tên NXB</th>
                                <th>Lựa chọn</th>
                            </tr>
                        </thead>

                        <tbody>

                            @foreach (var obj in Model)
                            {
                                <tr>
                                    <td class="font-weight-bold">@obj.Id</td>
                                    <td class="font-weight-bold">@obj.Name</td>
                                    <td>
                                        <button onclick="location.href='@Url.Action("Edit","Publisher",new{id = obj.Id})'" class="btn btn-primary">Chỉnh sửa</button>
                                        <button class="btn btn-danger"
                                                onclick="
                                                   if(confirm('Bạn có muốn xóa nhà xuất bản này?')){
                                                        location.href='@Url.Action("Delete","Publisher",new{id = @obj.Id})'
                                                    }
                                                ">
                                            Xóa
                                        </button>
                                    </td>
                                </tr>
                            }

                        </tbody>

                    </table>
                </div>

            </div>
        </div>
    </div>

</div>


<div class="modal fade" id="publisherAddModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Thêm Nhà xuất bản</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

       <form class="form-sample" method="post" asp-action="create">

            <div class="modal-body">
       
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group row">
                            <label class="col-sm-5 col-form-label">Tên nhà xuất bản</label>
                            <div class="col-sm-12">
                                <input type="text" class="form-control" name="Name" />
                            </div>
                        </div>
                    </div>
                   
                </div>
                
            </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Tạo</button>

            <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
          </div>
       </form>

    </div>
  </div>
</div>